# Generated by Django 3.0.3 on 2020-04-02 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myresume.Person'),
        ),
        migrations.AddField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myresume.Person'),
        ),
        migrations.AddField(
            model_name='interest',
            name='persons',
            field=models.ManyToManyField(to='myresume.Person'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myresume.Person'),
        ),
    ]
