# Generated by Django 3.0.3 on 2020-04-08 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myresume', '0003_auto_20200405_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
